package com.tiengine;

import com.tiengine.objects.GObjectHub;
import com.tiengine.scripting.RootScriptInterface;
import com.tiengine.scripting.ScriptEngine;

import org.junit.*;
import static org.junit.Assert.*;
import org.junit.runners.MethodSorters;
import org.junit.FixMethodOrder;
import org.luaj.vm2.LuaError;
import com.tiengine.objects.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'olegst' at '6/27/18 9:39 AM' with Gradle 2.10
 *
 * @author olegst, @date 6/27/18 9:39 AM
 */
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class LibraryTest {
    ScriptEngine se = null;
    static Logger logger = LoggerFactory.getLogger(GObject.class);

    @Before
    public void setUp() {
        se = new ScriptEngine();
    }

    @Test public void test_01_ScriptEngineRun() {
        assertTrue("se not inited", se != null);
        try {
            se.setExitHandler(new RootScriptInterface.ExitHandler() {
                @Override
                public void exit() {
                    System.out.println("Exit was requested");
                }
            });
            se.loadScript("src/test/lua/test.lua");
        } catch (LuaError e) {
            System.out.println(e.toString());
        }
    }

    @Test public void test_02_objectHub() {
        GObjectHub hub = new GObjectHub();
        hub.putObject(new GObject(), 0);
        hub.putObject(new GObject(), 0);
        GObject one_0 = new GObject();
        hub.putObject(one_0, 1);
        GObject one_1 = new GObject();
        hub.putObject(one_1, 1);

        assert(hub.objectCount(0) == 2);
        assert(hub.objectCount(1) == 2);
        assert(hub.objectCount() == 4);

        logger.info("in cluster");
        hub.interactInCluster(0);
        logger.info("unmutual");
        hub.interactBetweenClusters(0,1,false);
        logger.info("mutual");
        hub.interactBetweenClusters(0,1,true);
        hub.removeCluster(0);
        hub.removeObject(one_0);
        hub.removeObject(one_1);
        assert(hub.objectCount() == 0);
    }
}
